version: '3'

services:
  application:
    build: ./python
    volumes:
      - ./python:/usr/src/app
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 172.29.0.10
    container_name: python_app
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 172.29.0.20
    container_name: database

  ngrok:
    build: ./ngrok
    ports:
      - "32776:4040"
      - "32778:80"
    networks:
      app-network:
        ipv4_address: 172.29.0.30
    container_name: ngrok

  createwebhook:
    build: ./createWebhook
    networks:
      app-network:
        ipv4_address: 172.29.0.40
    container_name: createwebhook
    depends_on:
      - ngrok


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16